name: RSS Generation

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight (adjust as needed)

jobs:
  generate_rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Generate RSS feed
        run: node generate_rss.js > rss_feed.xml

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rss_feed.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
